### ISSUE TITLE
Install with nuxi init

### ISSUE THREAD

**Issue by atinux** [xiaoluoboding/nuxt3-starter#2]
You should be able to install the repo with `nuxi unit -t xiaoluoboding/nuxt3-starter`

Updating the install section instead of degit shall be better I believe.

**Comment by xiaoluoboding** [comment]
@Atinux Thanks for the advice, Do you mean the command is `npx nuxi init -t xiaoluoboding/nuxt3-starter`, I think it should be `init`, not `unit`.

**Comment by atinux** [comment]
Yes `npx nuxi init -t xiaoluoboding/nuxt3-starter` sorry it was a typo (I was on mobile)
